#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=10
STOP=15
 
start() {        
        echo start
        node /root/streznik.js
        # commands to launch application
}                 
 
stop() {          
        echo stop
        # commands to kill application 
}